<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
    <summary errors="1" failures="0" finished="true" name="Test Run: 0" tests="0" total_time="Finished in: 0.02 secs."/>
    <test location="C:\Users\Amala B Kannanthanam\workspace new\Python1\sites\aijo.py" status="error" test="aijo" time="0">
        <stdout/>
        <stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\Amala B Kannanthanam\.p2\pool\plugins\org.python.pydev.core_9.2.0.202110311311\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:\Users/Amala B Kannanthanam/workspace new/Python1/sites\aijo.py", line 24, in <module>
    driver.find_element_by_xpath("/html/body/div[1]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div[9]/div[1]/div[1]/a/div").click()
  File "C:\Users\Amala B Kannanthanam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 520, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Amala B Kannanthanam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Amala B Kannanthanam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Amala B Kannanthanam\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div[9]/div[1]/div[1]/a/div"}
  (Session info: chrome=96.0.4664.45)
Stacktrace:
Backtrace:
	Ordinal0 [0x009D6903+2517251]
	Ordinal0 [0x0096F8E1+2095329]
	Ordinal0 [0x00872848+1058888]
	Ordinal0 [0x0089D448+1233992]
	Ordinal0 [0x0089D63B+1234491]
	Ordinal0 [0x008C7812+1406994]
	Ordinal0 [0x008B650A+1336586]
	Ordinal0 [0x008C5BBF+1399743]
	Ordinal0 [0x008B639B+1336219]
	Ordinal0 [0x008927A7+1189799]
	Ordinal0 [0x00893609+1193481]
	GetHandleVerifier [0x00B65904+1577972]
	GetHandleVerifier [0x00C10B97+2279047]
	GetHandleVerifier [0x00A66D09+534521]
	GetHandleVerifier [0x00A65DB9+530601]
	Ordinal0 [0x00974FF9+2117625]
	Ordinal0 [0x009798A8+2136232]
	Ordinal0 [0x009799E2+2136546]
	Ordinal0 [0x00983541+2176321]
	BaseThreadInitThunk [0x767DFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77727A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77727A6E+238]

ERROR: Module: aijo could not be imported (file: C:\Users\Amala B Kannanthanam\workspace new\Python1\sites\aijo.py).
]]></stderr>
    </test>
    <launch mode="run">
        <launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Python1 aijo.py (1)"/>
]]></launch_memento>
    </launch>
</pydev-testsuite>
